/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\Cyberscene_Glb_V04.glb -k -K -T -j -M 
Files: .\public\Cyberscene_Glb_V04.glb [106.75MB] > D:\KPMG\Project\Prod\meta-cyber\Cyberscene_Glb_V04-transformed.glb [4.16MB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cyberscene_Glb_V04-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Cyberscene_Glb">
        <mesh name="Boxes" geometry={nodes.Boxes.geometry} material={materials['BoxesShape copy']} position={[-19.868, 1.485, 37.732]} />
        <mesh name="Cabinet" geometry={nodes.Cabinet.geometry} material={materials['CabinetShape copy']} position={[-19.998, 1.52, 37.729]} />
        <mesh name="Chair" geometry={nodes.Chair.geometry} material={materials['ChairShape copy']} position={[-18.085, 0.538, 37.22]} rotation={[0, 1.478, 0]} />
        <mesh name="CPU_Monitor" geometry={nodes.CPU_Monitor.geometry} material={materials['CPU_MonitorShape copy']} position={[-17.978, 1.573, 37.982]} />
        <mesh name="Outside_Plane" geometry={nodes.Outside_Plane.geometry} material={materials['Screenshot 2025-05-06 001035']} position={[-22.74, 2.518, 37.94]} scale={1.53} />
        <mesh name="Screens" geometry={nodes.Screens.geometry} material={materials['ScreensShape copy']} position={[-17.779, 1.594, 37.944]} />
        <mesh name="Table" geometry={nodes.Table.geometry} material={materials['TableShape copy']} position={[-18.13, 0.915, 37.941]} />
        <mesh name="TubeLight" geometry={nodes.TubeLight.geometry} material={materials['TubeLightShape copy']} position={[-18.08, 2.93, 38.43]} />
        <mesh name="Walls" geometry={nodes.Walls.geometry} material={materials['WallsShape copy']} position={[-17.609, 2.229, 36.092]} />
        <mesh name="Window_Frame" geometry={nodes.Window_Frame.geometry} material={materials['Window_FrameShape copy']} position={[-20.424, 2.279, 36.145]} />
        <mesh name="Window_Glass" geometry={nodes.Window_Glass.geometry} material={materials['S_RoomGlassBlue1 1']} position={[-20.424, 2.279, 36.145]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh name="BF_Nuclear" geometry={nodes.BF_Nuclear.geometry} material={materials['BF_NuclearShape copy']} position={[58.09, 17.684, -24.795]} />
        <mesh name="Boundry_wall" geometry={nodes.Boundry_wall.geometry} material={materials['Boundry_wallShape copy']} position={[11.036, 3.501, -1.081]} />
        <mesh name="Distillation" geometry={nodes.Distillation.geometry} material={materials['DistillationShape copy']} position={[-4.204, 11.627, -23.917]} />
        <mesh name="End_Storage_Tank" geometry={nodes.End_Storage_Tank.geometry} material={materials['End_Storage_TankShape copy']} position={[-1.953, 6.664, -62.047]} />
        <mesh name="FP_Pipes" geometry={nodes.FP_Pipes.geometry} material={materials['FP_PipesShape copy']} position={[65.99, 4.693, -12.206]} />
        <mesh name="Gate" geometry={nodes.Gate.geometry} material={materials['GateShape copy']} position={[52.177, 2.826, 71.84]} />
        <mesh name="Main_ground" geometry={nodes.Main_ground.geometry} material={materials['Main_groundShape copy']} position={[11.602, -0.239, 0]} />
        <mesh name="Pump_Turbine" geometry={nodes.Pump_Turbine.geometry} material={materials['Pump_turbineShape copy']} />
        <mesh name="Valve" geometry={nodes.Valve.geometry} material={materials['Pump_turbineShape copy']} position={[24.014, 2.629, -0.733]} />
        <mesh name="Pipe_01" geometry={nodes.Pipe_01.geometry} material={materials['Pipe_01Shape copy']} position={[10.77, 12.396, -40.841]} />
        <mesh name="Pipe_02" geometry={nodes.Pipe_02.geometry} material={materials['Pipe_02Shape copy']} position={[9.586, 8.322, 45.845]} />
        <mesh name="PreHeater" geometry={nodes.PreHeater.geometry} material={materials['PreHeaterShape copy']} position={[-34.927, 11.773, -20.738]} />
        <mesh name="Control_room_Exterior" geometry={nodes.Control_room_Exterior.geometry} material={materials['Control_Room_ExteriorShape copy']} position={[-22.502, 4.944, 31.937]} />
        <group name="Stage" position={[23.544, 1.518, 7.807]}>
          <mesh name="Stage_1" geometry={nodes.Stage_1.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
          <mesh name="Stage_2" geometry={nodes.Stage_2.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
        </group>
        <group name="Tank_01" position={[12.19, 6.478, 29.311]}>
          <mesh name="Tank_01_1" geometry={nodes.Tank_01_1.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
          <mesh name="Tank_01_2" geometry={nodes.Tank_01_2.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
          <mesh name="Tank_01_3" geometry={nodes.Tank_01_3.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
          <mesh name="Tank_01_4" geometry={nodes.Tank_01_4.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
        </group>
        <group name="Tank_02" position={[35.032, 6.478, 29.311]}>
          <mesh name="Tank_02_1" geometry={nodes.Tank_02_1.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
          <mesh name="Tank_02_2" geometry={nodes.Tank_02_2.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
          <mesh name="Tank_02_3" geometry={nodes.Tank_02_3.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
          <mesh name="Tank_02_4" geometry={nodes.Tank_02_4.geometry} material={materials['Oil_Storage_Tank1Shape copy']} />
        </group>
        <group name="CR_Chair" position={[-20.53, 1.011, 11.734]}>
          <mesh name="CR_Chair_1" geometry={nodes.CR_Chair_1.geometry} material={materials.SM_M_Chair_leather} />
          <mesh name="CR_Chair_2" geometry={nodes.CR_Chair_2.geometry} material={materials.SM_M_Chair_chrome} />
          <mesh name="CR_Chair_3" geometry={nodes.CR_Chair_3.geometry} material={materials.SM_M_Chair} />
          <mesh name="CR_Chair_4" geometry={nodes.CR_Chair_4.geometry} material={materials.SM_M_Chair_plastic} />
          <mesh name="CR_Chair_5" geometry={nodes.CR_Chair_5.geometry} material={materials['SM_M_Chair_chrome.002']} />
          <mesh name="CR_Chair_6" geometry={nodes.CR_Chair_6.geometry} material={materials.SM_M_Chair} />
          <mesh name="CR_Chair_7" geometry={nodes.CR_Chair_7.geometry} material={materials.SM_M_Chair_leather} />
          <mesh name="CR_Chair_8" geometry={nodes.CR_Chair_8.geometry} material={materials.SM_M_Chair_plastic} />
        </group>
        <mesh name="CR_Floor" geometry={nodes.CR_Floor.geometry} material={materials['CR_FloorShape copy']} position={[-16.243, 0.517, 12.832]} />
        <mesh name="CR_Main_wall" geometry={nodes.CR_Main_wall.geometry} material={materials['CR_Main_wallShape copy']} position={[-18.406, 3.392, 13.137]} scale={[0.982, 1, 1]} />
        <mesh name="CR_Roof" geometry={nodes.CR_Roof.geometry} material={materials['CR_RoofShape copy']} position={[-16.243, 6.094, 12.832]} />
        <mesh name="CR_Wall_Partition" geometry={nodes.CR_Wall_Partition.geometry} material={materials['CR_Wall_PartitionShape copy']} position={[-18.518, 3.306, 23.218]} />
        <group name="IT_R_Chair" position={[-16.191, 1.011, 27.849]}>
          <mesh name="IT_R_Chair_1" geometry={nodes.IT_R_Chair_1.geometry} material={materials['SM_M_Chair_chrome.002']} />
          <mesh name="IT_R_Chair_2" geometry={nodes.IT_R_Chair_2.geometry} material={materials.SM_M_Chair} />
          <mesh name="IT_R_Chair_3" geometry={nodes.IT_R_Chair_3.geometry} material={materials.SM_M_Chair_leather} />
          <mesh name="IT_R_Chair_4" geometry={nodes.IT_R_Chair_4.geometry} material={materials.SM_M_Chair_plastic} />
        </group>
        <group name="IT_Room_walls" position={[-16.214, 2.382, 27.87]}>
          <mesh name="IT_Room_walls_1" geometry={nodes.IT_Room_walls_1.geometry} material={materials['IT_Room_wallsShape copy']} />
          <mesh name="IT_Room_walls_2" geometry={nodes.IT_Room_walls_2.geometry} material={materials['IT_Room_wallsShape copy']} />
          <mesh name="IT_Room_walls_3" geometry={nodes.IT_Room_walls_3.geometry} material={materials['IT_Room_wallsShape copy']} />
        </group>
        <group name="Main_Desk" position={[-21.552, 0.912, 12.813]}>
          <mesh name="Main_Desk_1" geometry={nodes.Main_Desk_1.geometry} material={materials['Main_DeskShape copy']} />
          <mesh name="Main_Desk_2" geometry={nodes.Main_Desk_2.geometry} material={materials['Main_DeskShape copy']} />
        </group>
        <group name="Server_Walls" position={[-21.158, 2.382, 27.868]}>
          <mesh name="Server_Walls_1" geometry={nodes.Server_Walls_1.geometry} material={materials['Server_WallsShape copy']} />
          <mesh name="Server_Walls_2" geometry={nodes.Server_Walls_2.geometry} material={materials['Server_WallsShape copy']} />
          <mesh name="Server_Walls_3" geometry={nodes.Server_Walls_3.geometry} material={materials['Server_WallsShape copy']} />
        </group>
        <group name="Workstation" position={[-16.225, 0.92, 27.942]}>
          <mesh name="Workstation_1" geometry={nodes.Workstation_1.geometry} material={materials['WorkstationShape copy']} />
          <mesh name="Workstation_2" geometry={nodes.Workstation_2.geometry} material={materials['WorkstationShape copy']} />
        </group>
        <mesh name="polySurface4" geometry={nodes.polySurface4.geometry} material={materials.SM_TvBase} />
        <group name="SM_Cube9716" position={[-14.55, 1.331, 28.951]} rotation={[0, Math.PI / 2, 0]} scale={0.646}>
          <mesh name="SM_Cube9716_6" geometry={nodes.SM_Cube9716_6.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_7" geometry={nodes.SM_Cube9716_7.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_8" geometry={nodes.SM_Cube9716_8.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube9716_1" position={[-14.55, 1.331, 32.031]} rotation={[0, Math.PI / 2, 0]} scale={0.646}>
          <mesh name="SM_Cube9716_6" geometry={nodes.SM_Cube9716_6.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_7" geometry={nodes.SM_Cube9716_7.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_8" geometry={nodes.SM_Cube9716_8.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube9716_2" position={[-14.55, 1.331, 26.088]} rotation={[0, Math.PI / 2, 0]} scale={0.646}>
          <mesh name="SM_Cube9716_6" geometry={nodes.SM_Cube9716_6.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_7" geometry={nodes.SM_Cube9716_7.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_8" geometry={nodes.SM_Cube9716_8.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube9716_3" position={[-14.546, 1.331, 29.832]} rotation={[0, -Math.PI / 2, 0]} scale={0.646}>
          <mesh name="SM_Cube9716_6" geometry={nodes.SM_Cube9716_6.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_7" geometry={nodes.SM_Cube9716_7.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_8" geometry={nodes.SM_Cube9716_8.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube9716_4" position={[-14.546, 1.331, 27.008]} rotation={[0, -Math.PI / 2, 0]} scale={0.646}>
          <mesh name="SM_Cube9716_6" geometry={nodes.SM_Cube9716_6.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_7" geometry={nodes.SM_Cube9716_7.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_8" geometry={nodes.SM_Cube9716_8.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube9716_5" position={[-14.546, 1.331, 23.923]} rotation={[0, -Math.PI / 2, 0]} scale={0.646}>
          <mesh name="SM_Cube9716_6" geometry={nodes.SM_Cube9716_6.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_7" geometry={nodes.SM_Cube9716_7.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_8" geometry={nodes.SM_Cube9716_8.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube043" position={[-21.721, 1.129, 15.917]}>
          <mesh name="SM_Cube9716_6" geometry={nodes.SM_Cube9716_6.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_7" geometry={nodes.SM_Cube9716_7.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube9716_8" geometry={nodes.SM_Cube9716_8.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="polySurface6" position={[-14.548, 1.362, 29.192]} rotation={[0, Math.PI / 2, 0]} scale={0.815}>
          <mesh name="polySurface6_1" geometry={nodes.polySurface6_1.geometry} material={materials.SM_M_Monitor_display} />
          <mesh name="polySurface6_2" geometry={nodes.polySurface6_2.geometry} material={materials.SM_M_Monitor} />
          <mesh name="polySurface6_3" geometry={nodes.polySurface6_3.geometry} material={materials.SM_M_Metall} />
          <mesh name="polySurface6_4" geometry={nodes.polySurface6_4.geometry} material={materials.Screen1_Image} />
        </group>
        <group name="polySurface10" position={[-14.548, 1.362, 32.272]} rotation={[0, Math.PI / 2, 0]} scale={0.815}>
          <mesh name="polySurface10_1" geometry={nodes.polySurface10_1.geometry} material={materials.SM_M_Monitor_display} />
          <mesh name="polySurface10_2" geometry={nodes.polySurface10_2.geometry} material={materials.SM_M_Monitor} />
          <mesh name="polySurface10_3" geometry={nodes.polySurface10_3.geometry} material={materials.SM_M_Metall} />
          <mesh name="polySurface10_4" geometry={nodes.polySurface10_4.geometry} material={materials.Screen1_Image} />
        </group>
        <group name="polySurface18" position={[-14.548, 1.362, 26.328]} rotation={[0, Math.PI / 2, 0]} scale={0.815}>
          <mesh name="polySurface18_1" geometry={nodes.polySurface18_1.geometry} material={materials.SM_M_Monitor_display} />
          <mesh name="polySurface18_2" geometry={nodes.polySurface18_2.geometry} material={materials.SM_M_Monitor} />
          <mesh name="polySurface18_3" geometry={nodes.polySurface18_3.geometry} material={materials.SM_M_Metall} />
        </group>
        <group name="polySurface12" position={[-14.548, 1.362, 29.591]} rotation={[0, -Math.PI / 2, 0]} scale={0.815}>
          <mesh name="polySurface12_1" geometry={nodes.polySurface12_1.geometry} material={materials.SM_M_Monitor_display} />
          <mesh name="polySurface12_2" geometry={nodes.polySurface12_2.geometry} material={materials.SM_M_Monitor} />
          <mesh name="polySurface12_3" geometry={nodes.polySurface12_3.geometry} material={materials.SM_M_Metall} />
          <mesh name="polySurface12_4" geometry={nodes.polySurface12_4.geometry} material={materials.Screen1_Image} />
        </group>
        <group name="polySurface14" position={[-14.548, 1.362, 26.768]} rotation={[0, -Math.PI / 2, 0]} scale={0.815}>
          <mesh name="polySurface14_1" geometry={nodes.polySurface14_1.geometry} material={materials.SM_M_Monitor_display} />
          <mesh name="polySurface14_2" geometry={nodes.polySurface14_2.geometry} material={materials.SM_M_Monitor} />
          <mesh name="polySurface14_3" geometry={nodes.polySurface14_3.geometry} material={materials.SM_M_Metall} />
          <mesh name="polySurface14_4" geometry={nodes.polySurface14_4.geometry} material={materials.Screen1_Image} />
        </group>
        <group name="polySurface16" position={[-14.548, 1.362, 23.682]} rotation={[0, -Math.PI / 2, 0]} scale={0.815}>
          <mesh name="polySurface16_1" geometry={nodes.polySurface16_1.geometry} material={materials.SM_M_Monitor_display} />
          <mesh name="polySurface16_2" geometry={nodes.polySurface16_2.geometry} material={materials.SM_M_Monitor} />
          <mesh name="polySurface16_3" geometry={nodes.polySurface16_3.geometry} material={materials.SM_M_Metall} />
        </group>
        <mesh name="Screen_01" geometry={nodes.Screen_01.geometry} material={materials.Screen1_Image} position={[-14.548, 1.656, 26.27]} />
        <mesh name="Screen_02" geometry={nodes.Screen_02.geometry} material={materials.Screen1_Image} position={[-14.548, 1.656, 26.826]} rotation={[0, -Math.PI / 2, 0]} scale={0.815} />
        <mesh name="Screen_05" geometry={nodes.Screen_05.geometry} material={materials.Screen1_Image} position={[-14.548, 1.656, 29.649]} rotation={[0, -Math.PI / 2, 0]} scale={0.815} />
        <mesh name="Screen_03" geometry={nodes.Screen_03.geometry} material={materials.Screen1_Image} position={[-14.548, 1.362, 23.682]} rotation={[0, -Math.PI / 2, 0]} scale={0.815} />
        <mesh name="Screen_04" geometry={nodes.Screen_04.geometry} material={materials.Screen1_Image} position={[-14.548, 1.656, 29.134]} rotation={[0, Math.PI / 2, 0]} scale={0.815} />
        <mesh name="Screen_06" geometry={nodes.Screen_06.geometry} material={materials.Screen1_Image} position={[-14.548, 1.656, 32.214]} rotation={[0, Math.PI / 2, 0]} scale={0.815} />
        <mesh name="Screen_07" geometry={nodes.Screen_07.geometry} material={materials.Screen2_Image} position={[-22.55, 1.275, 18.739]} />
        <mesh name="Screen_08" geometry={nodes.Screen_08.geometry} material={materials.Screen2_Image} position={[-22.767, 1.275, 16.901]} />
        <mesh name="Screen_09" geometry={nodes.Screen_09.geometry} material={materials.Screen1_Image} position={[-22.102, 1.16, 15.908]} />
        <mesh name="Screen_10" geometry={nodes.Screen_10.geometry} material={materials.Screen2_Image} position={[-22.345, 1.654, 14.841]} />
        <mesh name="Screen_11" geometry={nodes.Screen_11.geometry} material={materials.Screen2_Image} position={[-22.767, 1.275, 10.168]} />
        <mesh name="Screen_12" geometry={nodes.Screen_12.geometry} material={materials.Screen1_Image} position={[-22.102, 1.16, 9.373]} />
        <mesh name="Screen_13" geometry={nodes.Screen_13.geometry} material={materials.Screen2_Image} position={[-22.55, 1.275, 7.62]} />
        <mesh name="Screen_14" geometry={nodes.Screen_14.geometry} material={materials['ExecutiveDashboard1 1']} position={[-23.395, 3.138, 9.885]} />
        <mesh name="Screen_15" geometry={nodes.Screen_15.geometry} material={materials['ExecutiveDashboard1 1']} position={[-23.395, 3.138, 15.043]} />
        <mesh name="Screen_16" geometry={nodes.Screen_16.geometry} material={materials.Server_console} position={[-21.308, 1.737, 27.083]} rotation={[Math.PI, 0, 0]} scale={41.211} />
        <mesh name="SM_CPU" geometry={nodes.SM_CPU.geometry} material={materials.BaseColor} position={[-21.827, 1.417, 5.56]} rotation={[Math.PI / 2, 1.489, -Math.PI / 2]} scale={10} />
        <mesh name="SM_CPU1" geometry={nodes.SM_CPU1.geometry} material={materials.BaseColor} position={[-21.827, 1.417, 7.552]} rotation={[Math.PI / 2, 1.489, -Math.PI / 2]} scale={10} />
        <mesh name="SM_CPU2" geometry={nodes.SM_CPU2.geometry} material={materials.BaseColor} position={[-21.827, 1.417, 11.177]} rotation={[Math.PI / 2, 1.489, -Math.PI / 2]} scale={10} />
        <mesh name="SM_CPU3" geometry={nodes.SM_CPU3.geometry} material={materials.BaseColor} position={[-21.827, 1.417, 17.735]} rotation={[Math.PI / 2, 1.489, -Math.PI / 2]} scale={10} />
        <group name="SM_Cube038" position={[-21.715, 1.129, 9.336]}>
          <mesh name="SM_Cube038_1" geometry={nodes.SM_Cube038_1.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube038_2" geometry={nodes.SM_Cube038_2.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube038_3" geometry={nodes.SM_Cube038_3.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube039" position={[-21.721, 1.129, 6.928]}>
          <mesh name="SM_Cube039_1" geometry={nodes.SM_Cube039_1.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube039_2" geometry={nodes.SM_Cube039_2.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube039_3" geometry={nodes.SM_Cube039_3.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube044" position={[-21.625, 1.129, 14.934]}>
          <mesh name="SM_Cube044_1" geometry={nodes.SM_Cube044_1.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube044_2" geometry={nodes.SM_Cube044_2.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube044_3" geometry={nodes.SM_Cube044_3.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube045" position={[-21.629, 1.129, 16.941]}>
          <mesh name="SM_Cube045_1" geometry={nodes.SM_Cube045_1.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube045_2" geometry={nodes.SM_Cube045_2.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube045_3" geometry={nodes.SM_Cube045_3.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube046" position={[-21.721, 1.129, 19.678]}>
          <mesh name="SM_Cube046_1" geometry={nodes.SM_Cube046_1.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube046_2" geometry={nodes.SM_Cube046_2.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube046_3" geometry={nodes.SM_Cube046_3.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube047" position={[-21.721, 1.129, 18.952]}>
          <mesh name="SM_Cube047_1" geometry={nodes.SM_Cube047_1.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube047_2" geometry={nodes.SM_Cube047_2.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube047_3" geometry={nodes.SM_Cube047_3.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube049" position={[-21.721, 1.129, 6.203]}>
          <mesh name="SM_Cube049_1" geometry={nodes.SM_Cube049_1.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube049_2" geometry={nodes.SM_Cube049_2.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube049_3" geometry={nodes.SM_Cube049_3.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube056" position={[-21.618, 1.129, 8.353]}>
          <mesh name="SM_Cube056_1" geometry={nodes.SM_Cube056_1.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube056_2" geometry={nodes.SM_Cube056_2.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube056_3" geometry={nodes.SM_Cube056_3.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="SM_Cube057" position={[-21.622, 1.129, 10.36]}>
          <mesh name="SM_Cube057_1" geometry={nodes.SM_Cube057_1.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube057_2" geometry={nodes.SM_Cube057_2.geometry} material={materials['SM_BadanKeyboard.001']} />
          <mesh name="SM_Cube057_3" geometry={nodes.SM_Cube057_3.geometry} material={materials['SM_TextKey.001']} />
        </group>
        <group name="polySurface20" position={[-22.55, 1.275, 18.739]}>
          <mesh name="polySurface20_1" geometry={nodes.polySurface20_1.geometry} material={materials.SM_M_Monitor_plastik} />
          <mesh name="polySurface20_2" geometry={nodes.polySurface20_2.geometry} material={materials.Screen2_Image} />
          <mesh name="polySurface20_3" geometry={nodes.polySurface20_3.geometry} material={materials['SM_M_Monitor.002']} />
          <mesh name="polySurface20_4" geometry={nodes.polySurface20_4.geometry} material={materials['SM_M_Chair_chrome.002']} />
          <mesh name="polySurface20_5" geometry={nodes.polySurface20_5.geometry} material={materials['SM_M_Chair_chrome.002']} />
        </group>
        <group name="polySurface26" position={[-22.55, 1.275, 14.514]}>
          <mesh name="polySurface26_1" geometry={nodes.polySurface26_1.geometry} material={materials.SM_M_Monitor_plastik} />
          <mesh name="polySurface26_2" geometry={nodes.polySurface26_2.geometry} material={materials.Screen2_Image} />
          <mesh name="polySurface26_3" geometry={nodes.polySurface26_3.geometry} material={materials['SM_M_Monitor.002']} />
          <mesh name="polySurface26_4" geometry={nodes.polySurface26_4.geometry} material={materials['SM_M_Chair_chrome.002']} />
          <mesh name="polySurface26_5" geometry={nodes.polySurface26_5.geometry} material={materials['SM_M_Chair_chrome.002']} />
        </group>
        <group name="polySurface22" position={[-22.767, 1.275, 16.901]}>
          <mesh name="polySurface22_1" geometry={nodes.polySurface22_1.geometry} material={materials.SM_M_Monitor_plastik} />
          <mesh name="polySurface22_2" geometry={nodes.polySurface22_2.geometry} material={materials.Screen2_Image} />
          <mesh name="polySurface22_3" geometry={nodes.polySurface22_3.geometry} material={materials['SM_M_Monitor.002']} />
          <mesh name="polySurface22_4" geometry={nodes.polySurface22_4.geometry} material={materials['SM_M_Chair_chrome.002']} />
          <mesh name="polySurface22_5" geometry={nodes.polySurface22_5.geometry} material={materials['SM_M_Chair_chrome.002']} />
        </group>
        <group name="polySurface34" position={[-22.767, 1.275, 6.27]}>
          <mesh name="polySurface34_1" geometry={nodes.polySurface34_1.geometry} material={materials.SM_M_Monitor_plastik} />
          <mesh name="polySurface34_2" geometry={nodes.polySurface34_2.geometry} material={materials.Screen2_Image} />
          <mesh name="polySurface34_3" geometry={nodes.polySurface34_3.geometry} material={materials['SM_M_Monitor.002']} />
          <mesh name="polySurface34_4" geometry={nodes.polySurface34_4.geometry} material={materials['SM_M_Chair_chrome.002']} />
          <mesh name="polySurface34_5" geometry={nodes.polySurface34_5.geometry} material={materials['SM_M_Chair_chrome.002']} />
        </group>
        <mesh name="SCreen_13" geometry={nodes.SCreen_13.geometry} material={materials.Screen2_Image} position={[-22.432, 1.654, 6.461]} />
        <group name="polySurface32" position={[-22.55, 1.275, 7.62]}>
          <mesh name="polySurface32_1" geometry={nodes.polySurface32_1.geometry} material={materials.SM_M_Monitor_plastik} />
          <mesh name="polySurface32_2" geometry={nodes.polySurface32_2.geometry} material={materials.Screen2_Image} />
          <mesh name="polySurface32_3" geometry={nodes.polySurface32_3.geometry} material={materials['SM_M_Monitor.002']} />
          <mesh name="polySurface32_4" geometry={nodes.polySurface32_4.geometry} material={materials['SM_M_Chair_chrome.002']} />
          <mesh name="polySurface32_5" geometry={nodes.polySurface32_5.geometry} material={materials['SM_M_Chair_chrome.002']} />
        </group>
        <group name="polySurface30" position={[-22.767, 1.275, 10.168]}>
          <mesh name="polySurface30_1" geometry={nodes.polySurface30_1.geometry} material={materials.SM_M_Monitor_plastik} />
          <mesh name="polySurface30_2" geometry={nodes.polySurface30_2.geometry} material={materials.Screen2_Image} />
          <mesh name="polySurface30_3" geometry={nodes.polySurface30_3.geometry} material={materials['SM_M_Monitor.002']} />
          <mesh name="polySurface30_4" geometry={nodes.polySurface30_4.geometry} material={materials['SM_M_Chair_chrome.002']} />
          <mesh name="polySurface30_5" geometry={nodes.polySurface30_5.geometry} material={materials['SM_M_Chair_chrome.002']} />
        </group>
        <group name="polySurface24" position={[-22.102, 1.16, 15.908]}>
          <mesh name="polySurface24_1" geometry={nodes.polySurface24_1.geometry} material={materials.SM_M_Monitor_display} />
          <mesh name="polySurface24_2" geometry={nodes.polySurface24_2.geometry} material={materials.SM_M_Monitor} />
          <mesh name="polySurface24_3" geometry={nodes.polySurface24_3.geometry} material={materials.SM_M_Metall} />
          <mesh name="polySurface24_4" geometry={nodes.polySurface24_4.geometry} material={materials.Screen1_Image} />
        </group>
        <group name="polySurface28" position={[-22.102, 1.16, 9.373]}>
          <mesh name="polySurface28_1" geometry={nodes.polySurface28_1.geometry} material={materials.SM_M_Monitor_display} />
          <mesh name="polySurface28_2" geometry={nodes.polySurface28_2.geometry} material={materials.SM_M_Monitor} />
          <mesh name="polySurface28_3" geometry={nodes.polySurface28_3.geometry} material={materials.SM_M_Metall} />
          <mesh name="polySurface28_4" geometry={nodes.polySurface28_4.geometry} material={materials.Screen1_Image} />
        </group>
        <group name="SM_SM_Table_Lamp001" position={[-22.154, 1.168, 9.953]}>
          <mesh name="SM_SM_Table_Lamp001_1" geometry={nodes.SM_SM_Table_Lamp001_1.geometry} material={materials.SM_M_Point_Lamp_Metall} />
          <mesh name="SM_SM_Table_Lamp001_2" geometry={nodes.SM_SM_Table_Lamp001_2.geometry} material={materials.SM_M_Lamp_glow} />
        </group>
        <group name="SM_SM_Table_Lamp002" position={[-22.154, 1.168, 16.532]}>
          <mesh name="SM_SM_Table_Lamp002_1" geometry={nodes.SM_SM_Table_Lamp002_1.geometry} material={materials.SM_M_Point_Lamp_Metall} />
          <mesh name="SM_SM_Table_Lamp002_2" geometry={nodes.SM_SM_Table_Lamp002_2.geometry} material={materials.SM_M_Lamp_glow} />
        </group>
        <mesh name="Corner_wall" geometry={nodes.Corner_wall.geometry} material={materials.lambert5} />
        <mesh name="Glass_partiiton" geometry={nodes.Glass_partiiton.geometry} material={materials.blinn1} position={[-19.693, 1.111, 23.226]} scale={[1, 1, 0.21]} />
        <mesh name="IT_Room_Glass" geometry={nodes.IT_Room_Glass.geometry} material={materials.blinn1} position={[-14.438, 1.111, 23.226]} scale={[1, 1, 0.21]} />
        <group name="Lights" position={[-18.445, 5.204, 17.257]}>
          <mesh name="Lights_1" geometry={nodes.Lights_1.geometry} material={materials.SM_LightBase} />
          <mesh name="Lights_2" geometry={nodes.Lights_2.geometry} material={materials.SM_Lights} />
        </group>
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Image_2} position={[-21.839, 0.551, 27.09]} rotation={[Math.PI, 0, 0]} scale={41.211} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.Image_0} position={[-21.839, 0.551, 27.09]} rotation={[Math.PI, 0, 0]} scale={41.211} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Image_1} position={[-21.839, 0.551, 27.09]} rotation={[Math.PI, 0, 0]} scale={41.211} />
        <mesh name="Server_grp_Server5" geometry={nodes.Server_grp_Server5.geometry} material={materials.Image_0} position={[-22.078, 1.536, 27.94]} />
        <mesh name="Skirting_ItRoom" geometry={nodes.Skirting_ItRoom.geometry} material={materials.lambert1} position={[-13.65, 0.57, 24.643]} />
        <group name="SM_Door03" position={[-16.558, 0.524, 23.295]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={1.524}>
          <mesh name="SM_Door03_1" geometry={nodes.SM_Door03_1.geometry} material={materials.T_Doors_B} />
          <mesh name="SM_Door03_2" geometry={nodes.SM_Door03_2.geometry} material={materials.MI_DoorGlass} />
        </group>
        <group name="SM_Door04" position={[-18.842, 0.524, 28.457]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={1.524}>
          <mesh name="SM_Door03_1" geometry={nodes.SM_Door03_1.geometry} material={materials.T_Doors_B} />
          <mesh name="SM_Door03_2" geometry={nodes.SM_Door03_2.geometry} material={materials.MI_DoorGlass} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Cyberscene_Glb_V04-transformed.glb')
